name: unusable_player
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  neat:
    path: /home/pm/Project/neat
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  freezed_annotation: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  freezed: ^0.14.5

flutter:
  uses-material-design: true
  fonts:
    - family: UnusablePlayerIcons
      fonts:
          - asset: fonts/UnusablePlayerIcons.ttf        
    - family: HindSiliguri
      fonts:
        - asset: fonts/HindSiliguri-Medium.ttf
        - asset: fonts/HindSiliguri-SemiBold.ttf
          weight: 600
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
